version: 2

jobs:
  docker-build:
    docker:
      - image: docker:latest

    steps:
      - setup_remote_docker
      - run: apk add --update bash git openssh
      - checkout

      - run:
          name: Docker Build
          command: |
            docker build -t reactioncommerce/base:latest .
            mkdir -p docker-cache
            docker save -o docker-cache/docker-image.tar reactioncommerce/base:latest
      - persist_to_workspace:
          root: docker-cache
          paths:
            - docker-image.tar

  test:
    docker:
      - image: docker:latest

    steps:
      - setup_remote_docker
      - checkout
      - attach_workspace:
          at: docker-cache
      - run:
          name: Load Docker Image
          command: |
            docker load < docker-cache/docker-image.tar
      - run:
          name: Test installed dependencies
          command: |
            docker run --rm reactioncommerce/base:latest bash test-script.sh

  docker-push:
    docker:
      - image: docker:latest

    steps:
      - setup_remote_docker
      - run: apk add --update bash git openssh
      - checkout
      - attach_workspace:
          at: docker-cache
      - run:
          name: Load Docker Image
          command: |
            docker load < docker-cache/docker-image.tar
      - run:
          name: Tag Docker Image
          command: |
            IMAGE_NAME=${DOCKER_IMAGE_NAME:-"reactioncommerce/base"}
            docker tag reactioncommerce/base:latest $IMAGE_NAME:$CIRCLE_TAG
            docker tag reactioncommerce/base:latest $IMAGE_NAME:latest
      - run:
          name: Docker Push
          command:
            IMAGE_NAME=${DOCKER_IMAGE_NAME:-"reactioncommerce/base"}
            docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
            docker push $IMAGE_NAME:$CIRCLE_TAG
            docker push $IMAGE_NAME:latest


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - docker-build:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - docker-build
          filters:
            tags:
              only: /.*/
      - docker-push:
          requires:
            - docker-build
            - test
          filters:
            # only run deploy on tags with format: v1.2.3
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]/
            # don't deploy on plain branch pushes
            branches:
              ignore: /.*/
