defaults: &defaults
  - setup_remote_docker
  - run: apk add --update bash git openssh
  - checkout

version: 2

jobs:
  build:
    docker:
      - image: docker:latest

    steps:
      <<: *defaults

      - run: .circleci/build.sh

      - save_cache:
          key: docker-cache-{{ .Revision }}
          paths:
            - ~/docker-cache

  test:
    docker:
      - image: docker:latest

    steps:
      <<: *defaults

      - restore_cache:
          key: docker-cache-{{ .Revision }}

      # run tests
      - run: .circleci/test.sh

  deploy:
    docker:
      - image: docker:latest

    steps:
      <<: *defaults

      - restore_cache:
          key: docker-cache-{{ .Revision }}

      - run: .circleci/deploy.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - build        
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
            - test
          filters:
            # only run deploy on tags with format: v1.2.3
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]/
            # don't deploy on plain branch pushes
            branches:
              ignore: /.*/
