version: 2

jobs:
  build:
    docker:
      - image: docker:latest

    steps:
      - setup_remote_docker
      - run: apk add --update bash git openssh
      - checkout

      - run:
          name: Docker Build
          command: |
            docker build -t reactioncommerce/base:latest .
            mkdir -p docker-cache
            docker save -o docker-cache/docker-image.tar reactioncommerce/base:latest
      - persist_to_workspace:
          root: docker-cache
          paths:
            - docker-image.tar

  test:
    docker:
      - image: docker:latest

    steps:
      - setup_remote_docker
      - checkout
      - attach_workspace:
          at: docker-cache
      - run:
          name: Load Docker Image
          command: |
            docker load < docker-cache/docker-image.tar
      - run:
          name: Test installed dependencies
          command: |
            docker run --rm reactioncommerce/base:latest bash test-script.sh

  deploy:
    docker:
      - image: docker:latest

    steps:
      - setup_remote_docker
      - run: apk add --update bash git openssh
      - checkout
      - attach_workspace:
          at: docker-cache
      - run: .circleci/deploy.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
            - test
          filters:
            # only run deploy on tags with format: v1.2.3
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]/
            # don't deploy on plain branch pushes
            branches:
              ignore: /.*/
